{{site-docker-name}}:
  build: ./{{site-path}}
  ports:
   - "1234:1234"
   - "21212:21212"
  volumes:
   - ./{{site-path}}:/usr/src/app
  links:
   - metrics
   - db
  hostname: "{{site-dockerised-svr}}"
  environment:
    MONGODB_URI: mongodb://192.168.59.103/{{db-name}}
    METRICS_HOST: 192.168.59.103
    METRICS_PORT: 2003
    APP_NAME: {{site-ns-name}}
  command: lein repl :headless :host 0.0.0.0 :port 21212
metrics:
  image: garycrawford/grafana_graphite:0.0.1
  volumes:
   - ./dashboards:/src/dashboards
  ports:
   - "80:80"
   - "2003:2003"
db:
  image: mongo:3.0.1
  ports:
  - "27017:27017"
  command: --smallfiles
